import{a as l,S as u,i as d}from"./assets/vendor-0344c242.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&c(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();l.defaults.headers.common["x-api-key"]="live_FPBqvPvKaWxt2krn6wY1uj5HHO0EKnvwR8P4EQF1dzWRf3kkk4WPVvfBm7dlsAPp";async function m(){return await l.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}async function p(e){return await l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`).then(o=>o.data)}const r={breedSelect:document.querySelector(".breed-select"),catInfo:document.querySelector(".cat-info"),loader:document.querySelector(".loader")};function a(e,o){e.classList.toggle("hidden",!o)}v();a(r.breedSelect,!1);a(r.loader,!0);const h=new u({select:r.breedSelect}),f={position:"topRight",message:"Oops! Something went wrong! Try reloading the page!"};async function g(){try{a(r.loader,!0),a(r.catInfo,!1);const e=r.breedSelect.value,o=await p(e);y(o)}catch{console.log(1),d.show(f)}a(r.loader,!1)}function y(e){const o=e[0].url,s=e[0].breeds[0],c=`<div class="card">
  <img class="img" src="${o}" alt="${s.name}"/>
      <div class="info">
        <h2 class="name">${s.name}</h2>
        <p><span class="description">Description: </span> ${s.description}</p>
        <p><span class="temperament">Temperament: </span> ${s.temperament}</p>   
       </div>
</div>`;r.catInfo.innerHTML=c,a(r.catInfo,!0)}async function v(){try{await m().then(e=>{const o=e.map(({id:s,name:c})=>({value:s,text:c}));console.log(o),h.setData(Array.from(o))}),a(r.breedSelect,!0),r.breedSelect.addEventListener("change",g)}catch{console.log(2),d.show(f)}a(r.loader,!1)}
//# sourceMappingURL=commonHelpers.js.map
